nyc_taxi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('DBT_DB_USER', 'nyc_tlc_user') }}"
      password: "{{ env_var('DBT_DB_PASS', 'nyc_tlc_password') }}"
      port: "{{ env_var('DBT_DB_PORT', 5433) | as_number }}"
      dbname: "{{ env_var('DBT_DB_NAME', 'nyc_tlc_dw') }}"
      schema: nyc_taxi_dw
      threads: 4
      keepalives_idle: 0 # default: 0, indicating the OS default
      connect_timeout: 10 # default: 10 seconds
      role: null
      search_path: null
      sslmode: prefer